scheduler:
  name: scheduler
  image:
    repository: "daskdev/dask"
    tag: "0.17.1"
    pullPolicy: IfNotPresent
  replicas: 1
  serviceType: "LoadBalancer"
  servicePort: 8786
  resources: {}
    # limits:
    #   cpu: 1.8
    #   memory: 6G
    # requests:
    #   cpu: 1.8
    #   memory: 6G

webUI:
  name: webui
  servicePort: 80

worker:
  name: worker
  image:
    repository: "daskdev/dask"
    tag: "0.17.1"
    pullPolicy: IfNotPresent
  replicas: 3
  default_resources:  # overwritten by resource limits if they exist
    cpu: 1
    memory: "4GiB"
  env:
    - name: EXTRA_CONDA_PACKAGES
      value: numba xarray -c conda-forge --yes
    - name: EXTRA_PIP_PACKAGES
      value: s3fs xarray --upgrade
  resources:
    limits:
      cpu: 2
      memory: "2G"
    requests:
      cpu: 2
      memory: "2G"

jupyter:
  name: jupyter
  enabled: false
