jupyterhub:
        hub:
          # output of first execution of 'openssl rand -hex 32'
          cookieSecret: "c52866ceed262083822dc6f2df479ae08d1275711d568e9c6a91140a0366e483"
          db:
            type: sqlite-memory

        proxy:
          # output of second execution of 'openssl rand -hex 32'
          secretToken: "b66745ddb5c23454e0d5aca84462f8eed3629ad79ecee0ca1663d66a454db6c1"

        singleuser:
          # from https://github.com/pangeo-data/pangeo/blob/master/gce/jupyter-config.yaml
          image:
            name: pangeo/notebook
            tag: e02bc75c40df01454dd01bd6ae55e0213ada7563
          defaultUrl: "/lab"
          serviceAccountName: daskkubernetes
          memory:
            guarantee: 500M 
            limit: 1G
          cpu:
            guarantee: "0.3"
            limit: "1"
          storage:
            type: none

        ingress:
          enabled: true
          annotations:
            kubernetes.io/tls-acme: "true"
          hosts:
            - js-169-94.jetstream-cloud.org
          tls:
           - hosts:
              - js-169-94.jetstream-cloud.org
             secretName: kubelego-tls-jupyterhub
