apiVersion: v1
kind: Pod
metadata:
  name: alpine
  namespace: default
spec:
  volumes:
      - name: alpine-volume
        persistentVolumeClaim:
          claimName: alpine-pv-claim
  containers:
      - image: alpine:3.2
        command:
          - /bin/sh
          - "-c"
          - "sleep 60m"
        imagePullPolicy: IfNotPresent
        name: alpine
        volumeMounts:
            - name: alpine-volume
              mountPath: /data/
  restartPolicy: Never
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alpine-pv-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
