hub:
  # output of first execution of 'openssl rand -hex 32'
  cookieSecret: ""
  db:
    type: sqlite-memory
  extraConfig:
    customPodHook: |
        from kubernetes import client
        def modify_pod_hook(spawner, pod):
            pod.spec.containers[0].security_context = client.V1SecurityContext(
                privileged=True,
                capabilities=client.V1Capabilities(
                    add=['SYS_ADMIN']
                )
            )
            return pod
        c.KubeSpawner.modify_pod_hook = modify_pod_hook

proxy:
  # output of second execution of 'openssl rand -hex 32'
  secretToken: ""

singleuser:
  # from https://github.com/pangeo-data/pangeo/blob/master/gce/jupyter-config.yaml
  image:
    name: daskdev/pangeo-notebook
    tag: 2018-02-22
  cmd: ['start-singleuser.sh']
  memory:
    guarantee: 1G
    limit: 2G
  storage:
    type: dynamic
    capacity: 1Gi
    dynamic:
      storageClass: rook-block

ingress:
  enabled: true
  annotations:
    kubernetes.io/tls-acme: "true"
  hosts:
    - js-xxx-xxx.jetstream-cloud.org
  tls:
   - hosts:
      - js-xxx-xxx.jetstream-cloud.org
     secretName: kubelego-tls-jupyterhub
