apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: jupyterhubcertificate
  namespace: jhub
spec:
  secretName: certmanager-tls-jupyterhub
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  issuerRef:
    name: letsencrypt-prod
  commonName: js-17-69.jetstream-cloud.org
  dnsNames:
  - js-17-69.jetstream-cloud.org
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - js-17-69.jetstream-cloud.org
