apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: pvc-test
 annotations:
   volume.beta.kubernetes.io/storage-class: standard
spec:
 accessModes:
  - ReadWriteOnce
 resources:
   requests:
     storage: 5Gi
