apiVersion: v1
kind: Pod
metadata:
  name: cvmfs
  namespace: default
spec:
  volumes:
      - name: cvmfs-volume
        persistentVolumeClaim:
          claimName: cvmfs-pv-claim
  containers:
      - image: zonca/cvmfs-client
        imagePullPolicy: IfNotPresent
        name: cvmfs-client
        volumeMounts:
            - name: cvmfs-volume
              mountPath: /cvmfs/
        securityContext:
            privileged: true
  restartPolicy: Never
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cvmfs-pv-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 20Gi
